-- Seed customer service page blocks

INSERT INTO page_blocks (page_id, type, content, sort_order, is_visible) VALUES
(5, 'split_content', '{"subtitle":"CUSTOMER CENTER","title":"무엇을 도와드릴까요?","description":"자주 묻는 질문, 공지사항, 1:1 문의를 통해 빠르게 안내해 드립니다.","cta_text":"1:1 문의하기","cta_url":"/my/inquiries/new","template":"default"}', 0, 1);

INSERT INTO page_blocks (page_id, type, content, sort_order, is_visible) VALUES
(6, 'text_content', '{"html":"<h2>배송 안내</h2><p>옥화당은 주문 확인 후 2~3일 내에 배송을 진행합니다. (공휴일/주말 제외)</p><h3>배송 비용</h3><ul><li><strong>기본 배송비:</strong> 3,000원 (도서산간 지역은 추가 비용 발생)</li><li><strong>무료 배송:</strong> 50,000원 이상 구매 시 무료</li><li><strong>배송업체:</strong> CJ대한통운</li><li><strong>배송 조회:</strong> 주문 상세 페이지에서 추적이 가능합니다.</li></ul><h3>배송 기간</h3><ul><li><strong>서울/경기:</strong> 1~2일</li><li><strong>지방:</strong> 2~3일</li><li><strong>도서산간:</strong> 3~5일</li></ul><p>배송 지연이나 이상 발생 시 고객센터로 문의해 주세요.</p>","textAlign":"left","template":"default"}', 0, 1);

INSERT INTO page_blocks (page_id, type, content, sort_order, is_visible) VALUES
(7, 'text_content', '{"html":"<h2>반품 및 교환 안내</h2><h3>반품/교환 가능 기간</h3><p>상품 수령 후 <strong>7일 이내</strong>에 신청 가능합니다. (단, 상품의 가치가 현저히 감소한 경우는 제외)</p><h3>반품/교환 불가 사유</h3><ul><li>사용 또는 개봉한 상품</li><li>고객님의 과실로 상품이 훼손된 경우</li><li>배송 후 결품이 발견된 경우 (고객센터로 즉시 연락)</li></ul><h3>반품/교환 절차</h3><ol><li>고객센터(1:1 문의)로 반품/교환 신청</li><li>접수 확정 후 지정된 주소로 상품 발송</li><li>상품 확인 후 환불/교환 처리 (2~3일)</li></ol><h3>환불 안내</h3><p>반품 상품 확인 후 3~5일 내에 결제 수단으로 환불됩니다. 무통장입금의 경우 등록된 계좌로 입금 처리됩니다.</p>","textAlign":"left","template":"default"}', 0, 1);

INSERT INTO page_blocks (page_id, type, content, sort_order, is_visible) VALUES
(8, 'text_content', '{"html":"<h2>이용약관</h2><p>본 약관은 옥화당(이하 \\\"당사\\\")이 운영하는 온라인 쇼핑몰에서 제공하는 서비스의 이용 조건을 정합니다.</p><h3>제1조 (목적)</h3><p>본 약관은 당사가 운영하는 온라인 쇼핑몰 서비스(이하 \\\"서비스\\\")의 이용에 관한 일반적인 조건을 규정합니다.</p><h3>제2조 (이용계약의 성립)</h3><p>이용자는 당사가 정한 이용 계약 조건에 동의한 후 서비스를 이용함으로써 이용 계약이 성립합니다.</p><h3>제3조 (서비스의 제공 및 변경)</h3><p>당사는 서비스의 내용, 이용 시간, 중단 등의 사항을 변경할 수 있으며, 이 경우 사전에 고지합니다.</p><h3>제4조 (결제)</h3><p>서비스 이용에 대한 대금 결제는 당사가 정한 결제 수단으로 할 수 있으며, 카드결제/무통장입금 등을 지원합니다.</p><h3>제5조 (환불)</h3><p>결제 취소 및 환불은 상품 수령 후 7일 이내에 신청 가능하며, 당사의 환불 정책에 따릅니다.</p><h3>제6조 (책임)</h3><p>당사는 서비스 제공 시 성실한 주의 의무를 다하나, 불가항력에 의한 서비스 중단은 책임지지 않습니다.</p><h3>제7조 (분쟁 해결)</h3><p>서비스 이용 관련 분쟁은 당사의 고객센터를 통해 해결하며, 합의가 이루어지지 않을 경우 관할 법원에 소송할 수 있습니다.</p>","textAlign":"left","template":"default"}', 0, 1);

INSERT INTO page_blocks (page_id, type, content, sort_order, is_visible) VALUES
(9, 'text_content', '{"html":"<h2>개인정보처리방침</h2><p>옥화당(이하 \\\"당사\\\")는 이용자의 개인정보를 소중히 취급하며, 「정보통신망 이용촉진 및 정보보호 등에 관한 법률」 등 관련 법령을 준수합니다.</p><h3>1. 수집하는 개인정보 항목</h3><ul><li><strong>필수:</strong> 이름, 이메일, 연락처, 주소</li><li><strong>선택:</strong> 생년월일, 성별 (회원 가입 시)</li><li><strong>자동 수집:</strong> IP 주소, 쿠키, 방문 기록</li></ul><h3>2. 개인정보의 수집 및 이용 목적</h3><p>수집한 개인정보는 서비스 제공, 계약 이행, 고객 관리, 마케팅/광고 등에 이용됩니다.</p><h3>3. 개인정보의 보유 기간</h3><p>이용자의 개인정보는 가입 해지 시까지 보유하며, 관련 법령에 따라 일정 기간 보존합니다. (계약이행 관련: 5년, 소비자분쟁: 3년)</p><h3>4. 개인정보의 제3자 제공</h3><p>당사는 이용자의 사전 동의 없이 개인정보를 제3자에게 제공하지 않습니다. 다만, 법률에 의한 경우나 서비스 제공에 필수적인 경우 예외로 합니다.</p><h3>5. 이용자 권리</h3><p>이용자는 자신의 개인정보에 대해 열람, 정정, 삭제, 처리 정지 요구 등 권리를 가지며, 언제든 고객센터를 통해 신청할 수 있습니다.</p><h3>6. 개인정보 보호 책임자</h3><p>책임자: 옥화당 고객센터 | 이메일: help@okhwandang.com</p>","textAlign":"left","template":"default"}', 0, 1);
